storybook:build:
  image: node:20.9.0
  stage: build
  script:
    - npm ci
    - npm run storybook:build
    - |
      echo -e "\e[0Ksection_start:`date +%s`:glpa_summary\r\e[0KHeader of the summary"
      echo "Storybook available at https://code0-tech.gitlab.io/-/base-ui/-/jobs/$CI_JOB_ID/artifacts/storybook-static/index.html"
      echo -e "\e[0Ksection_end:`date +%s`:glpa_summary\r\e[0K"
  environment:
    name: storybook/$CI_COMMIT_REF_SLUG
    url: https://code0-tech.gitlab.io/-/base-ui/-/jobs/$CI_JOB_ID/artifacts/storybook-static/index.html
    auto_stop_in: 7 days
  artifacts:
    paths:
      - storybook-static
    expire_in: 7 days
