storybook:build:
  image: node:20.9.0
  stage: build
  script:
    - npm ci
    - npm run storybook:build
    - |
      echo -e "\e[0Ksection_start:`date +%s`:glpa_summary\r\e[0KHeader of the summary"
      echo "Storybook available at https://code0-tech.gitlab.io/-/base-ui/-/jobs/$CI_JOB_ID/artifacts/storybook-static/index.html"
      echo -e "\e[0Ksection_end:`date +%s`:glpa_summary\r\e[0K"
  environment:
    name: storybook/$CI_COMMIT_REF_SLUG
    url: https://code0-tech.gitlab.io/-/base-ui/-/jobs/$CI_JOB_ID/artifacts/storybook-static/index.html
    auto_stop_in: 7 days
  artifacts:
    paths:
      - storybook-static
    expire_in: 7 days

storybook:test:
  image: ghcr.io/code0-tech/build-images/node-20.9-playwright:6.1
  stage: test
  script:
    - source ~/.asdf/asdf.sh
    - npm ci
    - npm run storybook:dev &
    - curl --fail -sv --retry 30 --retry-delay 3 --head --retry-all-errors http://127.0.0.1:6006
    - npm run storybook:test:all -- --ci
  artifacts:
    paths:
      - __snapshots__/__diff_output__
    expire_in: 7 days
